import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import localFont from "next/font/local";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const akiraFont = localFont({
  src: "../public/akira_expanded/Akira Expanded Demo.otf",
  variable: "--font-akira",
  display: "swap",
});

const futuraFont = localFont({
  src: "../public/futura-similar-fonts/Intrepid-Regular/intrepid.ttf",
  variable: "--font-futura",
  display: "swap",
});

export const metadata = {
  title: "Emoro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${akiraFont.variable} ${futuraFont.variable} h-full antialiased`}
    >
      <body className="min-h-full  bg-[#f7f2ec] m-3" suppressHydrationWarning >
          
        <AuthProvider>
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
